#!/usr/bin/env python3
"""ci_pipeline.py - the Campanian Ignimbrite findspots to RDF.

Reads the findspot table and geo-lod's own reading of it, and writes

    CI/rdf/ci_findspots.ttl         findspots, geometries, provenance
    CI/rdf/ci_site_annotations.ttl  the archaeological reading, separately

Inputs
------
``data/raw/ci/cifindspots_part_full.csv`` is the findspot table as it comes
out of ``campanian-ignimbrite-geo``: read only, and never edited here. Editing
it in this repository would fork it from the repository that maintains it, and
the fork would be invisible in both.

``data/curated/ci_site_annotations.csv`` is what geo-lod adds: which findspots
carry an archaeological record beyond what ``spatialtype`` already states. It
follows the pattern of ``sisal_site_annotations.csv`` down to the column names,
and for the same reason - an annotation that is not in the source may not hang
off the same provenance node as one that is.

What decides that a findspot is archaeological
----------------------------------------------
The ``spatialtype`` column, and the annotation file. Nothing else. Three
scripts used to carry a hand-written ``ARCHAEOLOGICAL_IDS`` set, and the sets
had drifted apart: the graph held nine sites, the map twelve. A reader
comparing the two would have found no way to tell which was right, because the
answer was in neither file but in two Python literals.

Modelling
---------
- every findspot is a ``geolod:CIFindspot``, plus ``prov:Entity``,
  ``pleiades:Place`` and ``fsl:Site``
- an archaeological one is additionally a ``geolod:CIArchaeologicalSite``
- geometry as a CRS-prefixed ``geo:wktLiteral``, bridged into CRM through
  ``crmgeo:SP6_Declarative_Place``
- the georeferencing activity produces the *geometry*, not the findspot. It
  used to produce the findspot and use it at the same time, which is a cycle:
  an entity generated by an activity that consumed it.
- all findspots hang off ``geolod:ci_volcanic_event``: ``crm:P7_took_place_at``
  where the site is archaeological, ``crm:P12_occurred_in_the_presence_of``
  otherwise

Run through main.py, or standalone from the repository root:

    python CI/ci_pipeline.py
"""

from __future__ import annotations

import csv
import sys
from pathlib import Path

from rdflib import Graph, Literal, Namespace, URIRef
from rdflib.namespace import DCTERMS, OWL, PROV, RDF, RDFS, SKOS, XSD

SCRIPT_DIR = Path(__file__).resolve().parent
ROOT = SCRIPT_DIR.parent
RAW_CSV = ROOT / "data" / "raw" / "ci" / "cifindspots_part_full.csv"
CURATED_CSV = ROOT / "data" / "curated" / "ci_site_annotations.csv"
RDF_DIR = SCRIPT_DIR / "rdf"
REPORT_DIR = SCRIPT_DIR / "report"

sys.path.insert(0, str(ROOT / "ontology"))
from geo_lod_utils import (  # noqa: E402
    GEO_LOD_RELEASE,
    add_feature_collection,
    add_generation_provenance,
    content_fingerprint,
    get_graph,
)

GEOLOD = Namespace("http://w3id.org/geo-lod/")
CI = Namespace("http://w3id.org/geo-lod/ci/")
CRM = Namespace("http://www.cidoc-crm.org/cidoc-crm/")
CRMARCHAEO = Namespace("http://www.cidoc-crm.org/extensions/crmarchaeo/")
CRMGEO = Namespace("http://www.ics.forth.gr/isl/CRMgeo/")
GEO = Namespace("http://www.opengis.net/ont/geosparql#")
SF = Namespace("http://www.opengis.net/ont/sf#")
FSL = Namespace("http://fuzzy-sl.squirrel.link/ontology/")
FSLD = Namespace("http://fuzzy-sl.squirrel.link/data/")
FOAF = Namespace("http://xmlns.com/foaf/0.1/")
PLEIADES = Namespace("https://pleiades.stoa.org/places/vocab#")

ORCID_FLO = URIRef("https://orcid.org/0000-0002-3246-3531")
ORCID_CO = URIRef("https://orcid.org/0000-0003-1100-6494")
CI_LICENSE = URIRef("https://creativecommons.org/licenses/by/4.0/")
CI_SOURCE_REPO = URIRef(
    "https://github.com/Research-Squirrel-Engineers/campanian-ignimbrite-geo"
)
CI_SOURCE_SCRIPT = URIRef(
    "https://github.com/Research-Squirrel-Engineers/"
    "campanian-ignimbrite-geo/blob/main/py/CI.py"
)

#: Columns read from the findspot table. Named rather than taken wholesale, so
#: that a column added upstream cannot silently change what ends up in the
#: graph.
CSV_COLUMNS = (
    "id", "label", "desc", "certainty", "certaintyinfo", "relatedto",
    "relatedtohow", "source", "sourcetype", "spatialtype", "methodtype",
    "agent", "methoddesc", "literature", "wkt",
)

STEPS = [
    "reading the findspot table",
    "reading the annotations",
    "findspots",
    "annotations",
    "provenance",
    "writing",
]


# ---------------------------------------------------------------------------
# Reading
# ---------------------------------------------------------------------------

def read_csv(path: Path, hint: str = "") -> list[dict]:
    if not path.exists():
        raise FileNotFoundError(f"{path} not found. {hint}".strip())
    with open(path, encoding="utf-8", newline="") as fh:
        return list(csv.DictReader(fh))


def text(row: dict, column: str) -> str:
    """Stripped cell, empty for the placeholders this table uses for null."""
    value = (row.get(column) or "").strip()
    return "" if value in (".", "??", "NULL", "nan", "None") else value


def split(value: str, sep: str = ";") -> list[str]:
    return [item.strip() for item in value.split(sep) if item.strip()]


def expand(term: str) -> URIRef:
    """A CURIE from the table as a full IRI."""
    for prefix, namespace in (("fsl:", FSL), ("fsld:", FSLD),
                              ("skos:", SKOS), ("geolod:", GEOLOD)):
        if term.startswith(prefix):
            return URIRef(str(namespace) + term[len(prefix):])
    return URIRef(term)


# ---------------------------------------------------------------------------
# Graph
# ---------------------------------------------------------------------------

def build_graph() -> Graph:
    g = get_graph()
    g.bind("fsl", FSL)
    g.bind("fsld", FSLD)
    g.bind("ci", CI)
    g.bind("pleiades", PLEIADES)
    return g


def wkt_literal(wkt: str) -> Literal:
    """CRS-prefixed geo:wktLiteral, in the form the rest of geo-lod writes."""
    return Literal(
        f"<http://www.opengis.net/def/crs/EPSG/0/4326> {wkt.strip()}",
        datatype=GEO["wktLiteral"],
    )


def archaeological_ids(rows: list[dict],
                       annotations: dict[str, dict]) -> set[str]:
    """Which findspots count as archaeological, and from where.

    Two readings, both explicit in a file: what the source states in
    ``spatialtype``, and what geo-lod adds in the annotation table. The union
    is what the graph types, and the two are told apart by their provenance,
    not by a comment.
    """
    from_source = {text(row, "id") for row in rows
                   if "ArchaeologicalSite" in text(row, "spatialtype")}
    from_curation = {ci_id for ci_id, note in annotations.items()
                     if (note.get("isArchaeologicalSite") or "").strip().lower()
                     == "true"}
    return from_source | from_curation


def add_findspots(g: Graph, rows: list[dict], arch: set[str]) -> list[URIRef]:
    event = GEOLOD["ci_volcanic_event"]
    uris: list[URIRef] = []

    for row in rows:
        ci_id = text(row, "id")
        site = CI[f"cisite_{ci_id}"]
        geom = CI[f"cisite_{ci_id}_geom"]
        activity = CI[f"cisite_{ci_id}_activity"]
        script_run = CI[f"cisite_{ci_id}_pyscript"]
        uris.append(site)

        is_arch = ci_id in arch

        for cls in (GEOLOD["CIFindspot"], PROV.Entity, PLEIADES["Place"],
                    FSL["Site"]):
            g.add((site, RDF.type, cls))
        if is_arch:
            g.add((site, RDF.type, GEOLOD["CIArchaeologicalSite"]))
            g.add((site, RDF.type, CRMARCHAEO["A2_Stratigraphic_Volume_Unit"]))

        label = text(row, "label")
        if label:
            g.add((site, RDFS.label, Literal(label, lang="en")))
            g.add((site, SKOS.prefLabel, Literal(label, lang="en")))

        desc = text(row, "desc")
        if desc:
            g.add((site, SKOS.scopeNote, Literal(desc, lang="en")))
            g.add((site, RDFS.comment, Literal(desc, lang="en")))

        certainty = text(row, "certainty")
        certainty_info = text(row, "certaintyinfo")
        if certainty:
            g.add((site, GEOLOD["hasCertaintyLevel"], expand(certainty)))
        if certainty_info:
            g.add((site, GEOLOD["hasCertaintyDescription"],
                   Literal(certainty_info, lang="en")))

        for spatial_type in split(text(row, "spatialtype")):
            g.add((site, GEOLOD["hasSpatialType"], expand(spatial_type)))

        literature = split(text(row, "literature"))
        for reference in literature:
            g.add((site, GEOLOD["hasLiteratureReference"], Literal(reference)))

        related = text(row, "relatedto")
        related_how = text(row, "relatedtohow")
        if related and related_how:
            predicate = expand(related_how)
            for target in split(related):
                if target.startswith("http"):
                    g.add((site, predicate, URIRef(target)))

        # An archaeological site is one the eruption reached; for the rest the
        # tephra is present and the claim stays weaker.
        if is_arch:
            g.add((event, CRM["P7_took_place_at"], site))
        else:
            g.add((event, CRM["P12_occurred_in_the_presence_of"], site))

        wkt = text(row, "wkt")
        if wkt:
            g.add((site, GEO["hasGeometry"], geom))
            g.add((geom, RDF.type, SF["Point"]))
            g.add((geom, RDF.type, CRMGEO["SP6_Declarative_Place"]))
            g.add((geom, GEO["asWKT"], wkt_literal(wkt)))
            if certainty:
                g.add((geom, GEOLOD["hasCertaintyLevel"], expand(certainty)))
            if certainty_info:
                g.add((geom, GEOLOD["hasCertaintyDescription"],
                       Literal(certainty_info, lang="en")))

        agents = []
        for orcid in split(text(row, "agent")):
            if orcid.startswith("http"):
                agent = URIRef(orcid)
                g.add((agent, RDF.type, FOAF["Person"]))
                g.add((agent, RDF.type, PROV.Agent))
                agents.append(agent)

        method = text(row, "methodtype")
        if method:
            g.add((activity, RDF.type, PROV.Activity))
            g.add((activity, RDF.type, expand(method)))
        source = text(row, "source")
        if source:
            g.add((activity, FSL["hasSource"], expand(source)))
        source_type = text(row, "sourcetype")
        if source_type:
            g.add((activity, FSL["hasSourceType"], expand(source_type)))
        method_desc = text(row, "methoddesc")
        if method_desc:
            g.add((activity, FSL["activityDesc"],
                   Literal(method_desc, lang="en")))
        for reference in literature:
            g.add((activity, GEOLOD["hasLiteratureReference"],
                   Literal(reference)))
        if certainty:
            g.add((activity, GEOLOD["hasCertaintyLevel"], expand(certainty)))

        # The georeferencing produced the coordinates, not the place: a
        # findspot exists whether or not anyone has put a point on it.
        if wkt:
            g.add((geom, PROV.wasGeneratedBy, activity))
        for agent in agents:
            g.add((site, PROV.wasAttributedTo, agent))
            g.add((activity, PROV.wasAssociatedWith, agent))

        g.add((site, PROV.wasGeneratedBy, script_run))
        g.add((site, PROV.wasAttributedTo, CI_SOURCE_SCRIPT))
        g.add((site, PROV.wasDerivedFrom, CI_SOURCE_REPO))
        g.add((script_run, RDF.type, PROV.Activity))
        g.add((script_run, PROV.wasAssociatedWith, CI_SOURCE_SCRIPT))

        g.add((site, DCTERMS.license, CI_LICENSE))
        for who in (ORCID_FLO, ORCID_CO):
            g.add((site, DCTERMS.creator, who))
            g.add((site, DCTERMS.rightsHolder, who))

    return uris


# ---------------------------------------------------------------------------
# Annotations - geo-lod's own reading, in its own graph
# ---------------------------------------------------------------------------

def add_annotation_source(g: Graph) -> None:
    source = GEOLOD["GeoLodCIAnnotations_DataSource"]
    g.add((source, RDF.type, GEOLOD["DataSource"]))
    g.add((source, RDF.type, OWL.NamedIndividual))
    g.add((source, RDFS.label,
           Literal("geo-lod CI findspot annotations", lang="en")))
    g.add((source, RDFS.comment,
           Literal("Archaeological readings added to Campanian Ignimbrite "
                   "findspots by the geo-lod project, beyond what the findspot "
                   "table states in its spatialtype column. Not part of "
                   "campanian-ignimbrite-geo and not reproducible from it.",
                   lang="en")))
    g.add((source, DCTERMS.creator, ORCID_FLO))
    g.add((source, DCTERMS.source, URIRef(
        "https://github.com/Research-Squirrel-Engineers/"
        "GeoScience-FAIRification-LOD")))
    g.add((source, DCTERMS.license, CI_LICENSE))


def add_annotations(g: Graph, annotations: dict[str, dict]) -> int:
    """The curated reading, with the same shape as the SISAL annotations.

    Screened and found nothing is a result, and a different one from never
    looked at - which is why the boolean is written even where the
    archaeological flag is false. For CI only the annotated findspots carry it
    so far; screening the remaining rows is S3f.
    """
    add_annotation_source(g)
    source = GEOLOD["GeoLodCIAnnotations_DataSource"]
    collection = GEOLOD["CI_Archaeological_Collection"]
    g.add((collection, RDF.type, GEO["FeatureCollection"]))
    g.add((collection, RDFS.label,
           Literal("CI findspots with an archaeological record", lang="en")))

    n_arch = 0
    for ci_id, note in sorted(annotations.items(), key=lambda kv: int(kv[0])):
        site = CI[f"cisite_{ci_id}"]

        def value(column: str) -> str:
            return (note.get(column) or "").strip()

        if value("screened").lower() == "true":
            g.add((site, GEOLOD["screenedForArchaeology"],
                   Literal(True, datatype=XSD.boolean)))
        g.add((site, PROV.wasDerivedFrom, source))

        if value("isArchaeologicalSite").lower() != "true":
            continue
        n_arch += 1
        g.add((site, RDF.type, GEOLOD["CIArchaeologicalSite"]))
        g.add((site, RDF.type, CRMARCHAEO["A2_Stratigraphic_Volume_Unit"]))
        g.add((collection, RDFS.member, site))
        if value("arch_category"):
            g.add((site, GEOLOD["archaeologicalCategory"],
                   Literal(value("arch_category"), lang="en")))
        if value("arch_broader_context"):
            g.add((site, GEOLOD["archaeologicalBroaderContext"],
                   GEOLOD[value("arch_broader_context")]))
        if value("arch_note"):
            g.add((site, SKOS.note, Literal(value("arch_note"), lang="en")))
        if value("arch_confidence"):
            g.add((site, GEOLOD["archaeologicalConfidence"],
                   Literal(value("arch_confidence"), lang="en")))
        if value("wikidata_qid"):
            g.add((site, SKOS.closeMatch,
                   URIRef("http://www.wikidata.org/entity/"
                          + value("wikidata_qid"))))
    return n_arch


# ---------------------------------------------------------------------------
# Writing
# ---------------------------------------------------------------------------

def header(title: str, inputs: list[Path]) -> str:
    """File header without a clock: release plus the fingerprint of the run."""
    return (
        f"# {title}\n"
        "# Generated by CI/ci_pipeline.py\n"
        f"# release: {GEO_LOD_RELEASE}\n"
        "# fingerprint (input data + generator): "
        f"{content_fingerprint([str(p) for p in inputs])}\n"
        f"# Source: {CI_SOURCE_REPO}\n\n"
    )


def write(g: Graph, path: Path, title: str, inputs: list[Path]) -> None:
    body = g.serialize(format="turtle")
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(header(title, inputs))
        fh.write(body)
    print(f"  ✓ {path.relative_to(ROOT)}  ({len(g):,} triples)")


class Tee:
    """Writes simultaneously to stdout and the report file."""

    def __init__(self, filepath: Path):
        self.file = open(filepath, "w", encoding="utf-8", newline="\n")
        self.stdout = sys.stdout
        try:
            self.stdout.reconfigure(encoding="utf-8", errors="replace")
        except (AttributeError, ValueError):
            pass
        sys.stdout = self

    def write(self, data):
        self.stdout.write(data)
        self.file.write(data)

    def flush(self):
        self.stdout.flush()
        self.file.flush()

    def close(self):
        sys.stdout = self.stdout
        self.file.close()


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def build() -> bool:
    step = iter(STEPS)

    print("\n" + "=" * 72)
    print("  Campanian Ignimbrite findspots to RDF")
    print("=" * 72)
    print(f"  Input:  {RAW_CSV.relative_to(ROOT)}")
    print(f"          {CURATED_CSV.relative_to(ROOT)}")

    print(f"\n  ▶ {next(step)}")
    rows = read_csv(RAW_CSV,
                    "It moved to data/raw/ci/ in S3e; the copies in CI/ and "
                    "archaeo-connect/ are gone.")
    missing = [c for c in CSV_COLUMNS if c not in (rows[0] if rows else {})]
    if missing:
        raise ValueError(f"columns missing from {RAW_CSV.name}: "
                         f"{', '.join(missing)}")
    ids = [text(row, "id") for row in rows]
    if len(set(ids)) != len(ids):
        raise ValueError("duplicate id in the findspot table")
    without_geometry = [i for i, row in zip(ids, rows) if not text(row, "wkt")]
    print(f"    {len(rows)} findspots, {len(rows) - len(without_geometry)} "
          f"with a geometry")
    if without_geometry:
        print(f"    ⚠  no geometry: {', '.join(without_geometry)} - the SHACL "
              f"shape requires one")

    print(f"\n  ▶ {next(step)}")
    annotations = {text(row, "ci_id"): row for row in read_csv(
        CURATED_CSV, "It is maintained by hand in geo-lod and is not an "
                     "export of campanian-ignimbrite-geo.")}
    unknown = sorted(set(annotations) - set(ids), key=lambda v: int(v or 0))
    if unknown:
        raise ValueError(f"annotated ids not in the findspot table: "
                         f"{', '.join(unknown)}")
    arch = archaeological_ids(rows, annotations)
    from_source = {text(row, "id") for row in rows
                   if "ArchaeologicalSite" in text(row, "spatialtype")}
    print(f"    {len(annotations)} annotated findspots")
    print(f"    {len(arch)} archaeological: {len(from_source)} from "
          f"spatialtype, {len(arch - from_source)} added by curation")

    print(f"\n  ▶ {next(step)}")
    g = build_graph()
    uris = add_findspots(g, rows, arch)
    add_feature_collection(
        g=g,
        collection_uri=CI["CIFindspotCollection"],
        label="Campanian Ignimbrite Findspot Collection",
        members=uris,
    )

    print(f"\n  ▶ {next(step)}")
    ann = build_graph()
    n_arch = add_annotations(ann, annotations)
    print(f"    {n_arch} archaeological findspots from the annotation table")

    print(f"\n  ▶ {next(step)}")
    add_generation_provenance(
        g,
        CI["ci_findspots_dataset"],
        CI["ci_findspots_generation"],
        inputs=[str(RAW_CSV), __file__],
        agents=[ORCID_FLO, CI_SOURCE_REPO],
        label="CI findspot RDF generation",
    )
    # Every findspot's script run hangs off the generation of this dump.
    # prov:wasInformedBy rather than prov:hadMember: the dataset is not a
    # prov:Collection, and membership is already in the FeatureCollection.
    for ci_id in ids:
        g.add((CI[f"cisite_{ci_id}_pyscript"], PROV.wasInformedBy,
               CI["ci_findspots_generation"]))
    add_generation_provenance(
        ann,
        CI["ci_site_annotations_dataset"],
        CI["ci_site_annotations_generation"],
        inputs=[str(CURATED_CSV), __file__],
        agents=[ORCID_FLO],
        label="geo-lod CI findspot annotations",
    )

    print(f"\n  ▶ {next(step)}")
    RDF_DIR.mkdir(parents=True, exist_ok=True)
    write(g, RDF_DIR / "ci_findspots.ttl",
          "ci_findspots.ttl — Campanian Ignimbrite findspot instance data",
          [RAW_CSV, Path(__file__)])
    write(ann, RDF_DIR / "ci_site_annotations.ttl",
          "ci_site_annotations.ttl — geo-lod's archaeological reading of the "
          "CI findspots",
          [CURATED_CSV, Path(__file__)])

    return True


def main() -> int:
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    tee = Tee(REPORT_DIR / "report.txt")
    try:
        ok = build()
    except Exception:
        import traceback
        traceback.print_exc()
        ok = False
    finally:
        tee.close()
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
